# Generated by Django 5.2.1 on 2025-06-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='calendar',
            new_name='dete',
        ),
    ]
